import React from 'react'

const LazyComponent = () => {
  return (
    <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at nibh condimentum, vulputate elit eu, mattis erat. Aenean vel pulvinar ex. Nunc molestie urna quis lacus pretium, sit amet tempor velit blandit. Quisque iaculis varius feugiat. Integer blandit velit purus, id blandit libero bibendum id. Pellentesque ornare, quam at euismod rutrum, erat leo dapibus libero, nec efficitur augue lectus ac leo. Nulla gravida semper efficitur. Vivamus tristique posuere velit, ullamcorper vestibulum turpis molestie nec. Quisque est ipsum, tincidunt in sem vel, sagittis efficitur enim. Ut eleifend tempus turpis et aliquet. Mauris luctus, felis sed vulputate dapibus, nisi dui finibus lorem, ut lobortis diam est eget turpis. Proin venenatis gravida enim. Pellentesque ipsum sapien, pharetra id mi eget, tempus sagittis nibh. Nunc purus sapien, egestas faucibus molestie in, luctus quis lectus.

In id maximus quam, vel cursus mi. Vivamus consequat vel lacus vitae dictum. Nunc hendrerit cursus nibh sit amet aliquam. Etiam ac fringilla augue, nec laoreet libero. Fusce et commodo ligula. Nam ultrices at purus non sodales. Nam lorem mauris, placerat at blandit vitae, lacinia ac ligula. Donec lobortis laoreet risus ac dictum.

Nullam vestibulum nulla vitae feugiat iaculis. Etiam congue, enim vel cursus tincidunt, augue diam eleifend purus, id pretium mauris nisi vel lorem. Cras ornare dui at elit vehicula, a dignissim lacus hendrerit. Praesent euismod sodales nisi. Maecenas placerat vitae nisl eget pulvinar. Duis iaculis viverra lectus, quis malesuada metus pulvinar auctor. Suspendisse et nisi sit amet tellus ultricies condimentum a eu sem. Maecenas neque lacus, porttitor ut nisl eu, convallis euismod diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eget laoreet mauris. Sed viverra est ut semper semper. Fusce sit amet mi non arcu pellentesque hendrerit. Donec dolor elit, aliquam et condimentum vitae, ullamcorper quis risus. Praesent dolor libero, finibus eget libero ac, eleifend varius elit.

Nulla vel malesuada magna. Maecenas convallis nibh augue, sed gravida massa cursus nec. Etiam et maximus lorem, eget pharetra tellus. Pellentesque ac turpis vitae felis venenatis accumsan. Sed nibh est, lobortis ut ante a, laoreet suscipit nunc. Proin sed diam convallis dolor feugiat porta. Nullam a massa quis velit luctus auctor a non magna. Aliquam egestas malesuada luctus. Nullam porttitor neque a fringilla tristique. Morbi eu sapien ut augue ornare imperdiet at ac sem. Nulla vehicula venenatis risus, at pulvinar purus dignissim at. Phasellus in porttitor mi. Sed cursus ullamcorper est in egestas.

Integer at consequat quam. Donec fringilla eros id est semper efficitur. Donec commodo metus sed placerat auctor. Donec ultrices facilisis est non lacinia. Sed ornare magna risus, vitae auctor nisl sodales non. Quisque consequat aliquet mattis. Morbi dignissim auctor nibh, quis scelerisque sapien ultricies nec. Maecenas vitae eros sed nibh dignissim viverra. Cras viverra odio orci, sed blandit justo tincidunt volutpat. Maecenas cursus velit a turpis mattis vulputate. Ut consequat enim efficitur purus malesuada placerat. Suspendisse blandit vulputate lorem, vel molestie lectus auctor vel. Nullam lectus libero, egestas nec rutrum ut, semper non sapien. Cras feugiat nulla et metus cursus sollicitudin. Nullam pharetra risus et scelerisque viverra.

Aliquam sollicitudin consequat diam, quis finibus libero mattis eget. Suspendisse suscipit tempor pretium. Donec tincidunt consequat orci nec laoreet. Mauris ipsum dui, laoreet eu felis eu, malesuada viverra metus. Ut consectetur iaculis fermentum. Etiam accumsan enim pulvinar lectus luctus eleifend. Proin nec odio et urna egestas faucibus.

Nam sed tincidunt lacus, ut iaculis ex. Donec iaculis metus sit amet elit auctor, sed dapibus elit luctus. Morbi eget feugiat magna. Mauris at orci sit amet purus posuere dignissim. Integer semper maximus sem, id tempus est vulputate et. Maecenas urna lacus, fringilla vitae lacinia vel, dapibus eu turpis. Integer ac ante cursus, elementum purus ut, sodales arcu. Donec eu ante enim. Curabitur suscipit orci sed leo vulputate, sed porta quam sagittis. Nam consequat risus velit, id hendrerit ante tempor sed. Duis pharetra blandit mauris nec dapibus. Quisque aliquet odio sed imperdiet tempor. Etiam facilisis hendrerit erat at condimentum. Cras a posuere lorem, et lobortis nunc. Sed non mollis lacus.

Aliquam euismod arcu ac nibh hendrerit scelerisque tempus ut tellus. Ut auctor sapien sit amet arcu blandit, a volutpat velit euismod. Mauris non lobortis felis. Sed fringilla in mauris quis euismod. Sed laoreet felis vel efficitur interdum. Sed pellentesque nisl vitae felis blandit, non aliquet nunc dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut purus dolor, venenatis nec dui non, faucibus laoreet felis. Donec volutpat neque in sodales convallis. Integer scelerisque, nibh at elementum efficitur, est tortor rhoncus tortor, ut eleifend urna ligula nec tellus. Quisque imperdiet arcu vitae nisi hendrerit ornare. Curabitur auctor accumsan nisl, ac ultrices ante consectetur id.

Aliquam rhoncus odio eget orci gravida, in pellentesque nunc faucibus. Pellentesque rhoncus varius aliquam. Donec sit amet tempus libero. Mauris id elit eget ligula egestas feugiat. Praesent vitae suscipit purus. Suspendisse potenti. Nulla in tortor ac augue rhoncus facilisis. Quisque lacus orci, tempus vehicula viverra non, tempor ut enim.

Vivamus quis ex lacinia, volutpat ante ac, rutrum nisi. Phasellus condimentum sit amet mi eget vulputate. Nullam in lorem leo. Nullam quis massa suscipit, lobortis tellus nec, interdum orci. Nullam tempor, nibh at fringilla pulvinar, enim ex posuere metus, et pretium diam ligula in mauris. Morbi porttitor eros interdum hendrerit cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a diam quis orci pharetra iaculis at eu turpis.

Quisque eget ex egestas, facilisis quam a, ullamcorper libero. Curabitur ornare metus diam, sit amet facilisis neque tristique a. Morbi gravida arcu eget sem scelerisque, eget venenatis orci ullamcorper. Sed sit amet aliquet dolor. In pretium sapien eget urna dignissim blandit. Etiam mauris nisl, condimentum id urna id, venenatis auctor nulla. Mauris pulvinar ex id erat sagittis, non eleifend mi vulputate. Vivamus augue tellus, fringilla ut magna vel, tincidunt luctus felis. Donec egestas leo a urna rutrum congue. Nam interdum porttitor mauris sed interdum. Curabitur efficitur libero mi, nec dictum diam rhoncus ut. Vestibulum ac ornare nisl, ut viverra tellus.

Morbi finibus ex nec convallis feugiat. Duis a finibus justo, non ultricies turpis. Mauris pellentesque nisi vel tortor blandit cursus. Pellentesque finibus ligula sit amet accumsan vestibulum. Quisque tempor commodo purus. Aenean rhoncus dignissim lectus, nec varius tellus vulputate non. Nulla varius facilisis est nec vestibulum. Cras vel dolor condimentum, gravida nisl ut, luctus lorem. In molestie facilisis eros, ac laoreet nisi laoreet vel. Phasellus blandit, tellus et tristique porttitor, enim lorem vulputate tellus, ut sollicitudin ex quam sed ex.

Phasellus at lorem et nibh dignissim blandit a at lectus. Fusce in mi sollicitudin, pellentesque tortor et, posuere lorem. Pellentesque molestie, libero ut ultricies congue, eros odio condimentum erat, ut aliquam ligula metus id lorem. Morbi efficitur tempus placerat. In ac metus posuere nulla facilisis facilisis. Ut ut massa mauris. Etiam et purus metus. Sed sagittis tempus lectus nec porta. Vivamus sed malesuada sapien. Nulla id nulla tellus. Maecenas sapien lectus, semper et est sit amet, ullamcorper tempus dolor. Etiam id interdum metus, ut luctus ex. Vestibulum gravida mauris nisi, vitae maximus leo sollicitudin quis. Nulla eu tempor tellus, vel posuere dui.

Morbi nec lorem lacus. Integer et orci eget enim pretium tristique ut sed velit. Quisque scelerisque tempus libero nec porttitor. Mauris massa nunc, volutpat sit amet erat eget, pellentesque imperdiet quam. Maecenas tempor volutpat mauris, in vestibulum nulla maximus in. Ut luctus sapien quis leo tempus, nec pharetra neque ullamcorper. Nulla facilisi. Aenean auctor risus tortor. In mollis blandit dolor. Sed suscipit velit lorem, sed egestas nunc imperdiet eget. Sed iaculis, leo vel porttitor tincidunt, ex nunc hendrerit risus, sed iaculis purus diam a nunc.

Praesent sit amet tortor in erat accumsan sollicitudin gravida sed dolor. Vestibulum iaculis vitae velit et imperdiet. Integer quis mauris nibh. Donec ultrices ipsum eu lacus egestas varius. Phasellus luctus at purus in faucibus. Sed venenatis magna arcu, nec sollicitudin est cursus sit amet. Sed vitae arcu luctus, ornare turpis quis, posuere urna. Nullam porttitor et est non sollicitudin.

Suspendisse eget elit id lorem ornare rutrum. Sed rhoncus libero eu nulla venenatis, et pharetra justo vehicula. Fusce id sollicitudin dui. Aliquam nec purus in elit faucibus laoreet. Morbi consequat venenatis ante, eu condimentum libero. Quisque at hendrerit risus. Suspendisse convallis, mi id tincidunt faucibus, lacus augue rhoncus tortor, a scelerisque nunc metus eget tortor. Vivamus quis justo vel lorem maximus aliquam vitae finibus arcu. Ut pharetra diam a purus aliquam tincidunt. Vivamus a ex pharetra, sagittis ligula vel, dictum diam.

Sed et ullamcorper augue. In egestas, risus in sodales eleifend, sem tortor molestie orci, ut rhoncus ex libero eu ipsum. Etiam enim arcu, interdum aliquet placerat et, pretium sit amet eros. Pellentesque pulvinar tellus sit amet nisl maximus vestibulum. Nulla molestie erat at eros semper, non sollicitudin magna vestibulum. Maecenas bibendum quis mi ac gravida. Fusce quis elit aliquet, mattis nunc ac, faucibus nulla. Aliquam lectus felis, gravida ac vehicula id, congue facilisis dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse maximus diam sed pulvinar lobortis. Phasellus egestas, dolor viverra malesuada cursus, elit lacus interdum velit, nec tincidunt justo tortor et magna.

Donec tempor a velit at ornare. Curabitur interdum leo in sapien placerat malesuada. Donec posuere, enim ac feugiat dictum, orci metus lobortis risus, sed posuere tellus dolor ac dolor. Vestibulum urna ex, elementum ac lacinia vel, tincidunt eget erat. Sed at turpis fermentum, ornare risus nec, pulvinar mi. Maecenas bibendum metus et mattis scelerisque. Ut ligula arcu, tristique ac fringilla nec, convallis et dui. Praesent egestas nibh vitae mauris scelerisque tincidunt. Etiam fringilla egestas urna non vestibulum.

Duis ac tincidunt lacus. Integer fringilla ante eget leo luctus, sit amet sodales ipsum suscipit. Mauris sit amet turpis sagittis, sodales nunc sit amet, vestibulum nunc. Integer at posuere velit. Cras laoreet sem luctus nulla cursus gravida. Praesent congue nulla quis odio pellentesque volutpat. Nam tincidunt accumsan varius. Pellentesque ut ultricies ipsum, vel sagittis felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur laoreet in ante sit amet mollis. Maecenas nec massa vitae erat porta sodales ac id leo. Nam nec dignissim nunc.

Nullam non nulla efficitur, faucibus mi non, commodo turpis. Sed id facilisis sapien, eget eleifend quam. Etiam interdum augue ac fermentum mollis. Integer velit nulla, iaculis a justo quis, ullamcorper sodales urna. Donec odio odio, congue a ante eget, vulputate lacinia lacus. Phasellus ornare lectus justo, vitae volutpat ligula elementum vitae. Fusce pretium fringilla lacus, ultrices sodales felis posuere ut. Praesent nunc nisl, tincidunt at pulvinar a, lacinia vitae dolor. Aliquam vel enim venenatis ipsum aliquam fringilla ut nec velit. Donec pulvinar lacus a lorem aliquet posuere. Morbi sit amet bibendum justo. Aliquam semper mi id elit egestas porta. Sed dictum, odio eget porta pulvinar, purus sem tincidunt risus, eget finibus dolor velit eu erat. Proin ullamcorper euismod dolor, eu lobortis nisi vehicula ut. Morbi sed placerat metus.

Aenean lacus ipsum, sagittis id consectetur nec, pharetra et neque. Suspendisse et hendrerit metus, et sagittis nisl. Aenean ac molestie nisi, vel interdum risus. Quisque blandit magna nec ultrices posuere. Integer luctus tempus elit, eu fringilla metus suscipit sit amet. Maecenas eu lectus justo. Sed quis vestibulum metus, vitae rhoncus quam.

Donec et urna diam. Vestibulum vitae nunc condimentum, consectetur ex nec, commodo velit. Integer malesuada est eget orci egestas aliquam. Nunc pharetra efficitur orci id suscipit. Nunc ac condimentum lacus. Maecenas eget nulla sit amet mi dapibus aliquam vel sed nunc. Integer convallis sodales magna id tempor.

In venenatis, magna in volutpat auctor, libero lorem sagittis orci, id placerat libero ex a nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras interdum rhoncus odio, feugiat ultricies enim consequat in. Nam sit amet lacinia libero. Praesent et quam id sapien pharetra iaculis congue at dolor. Quisque sit amet laoreet leo. Donec ut lobortis risus. Nullam facilisis neque vel aliquet aliquam. Nullam facilisis vel purus quis tincidunt. Curabitur nisi est, blandit nec nisl ac, maximus pharetra lectus. Phasellus sapien sem, pulvinar vitae vestibulum vitae, laoreet blandit mauris.

Nulla porta leo vel purus hendrerit, faucibus feugiat nisl feugiat. Curabitur non consequat dui. In aliquet urna quis tristique malesuada. Fusce consequat, felis eget porttitor luctus, quam nisl consectetur dolor, eget lobortis ipsum nulla id metus. Praesent sed condimentum lacus, faucibus feugiat nulla. Sed eget odio a nisi tempor feugiat id ullamcorper sem. Fusce eget posuere lorem, eu laoreet risus. Vestibulum quis scelerisque dolor. Maecenas in nulla laoreet, placerat libero in, rutrum urna. Sed id ex erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras id eleifend nisl, eu congue leo.

Nam lectus turpis, consequat vel ligula eget, ullamcorper vestibulum massa. Pellentesque pharetra magna sit amet magna mollis molestie. Sed aliquet blandit odio ut suscipit. Etiam dapibus ipsum turpis, non gravida nisl consectetur eu. Nullam nec consequat neque. Maecenas a ullamcorper arcu. Morbi venenatis convallis fringilla. Nullam egestas diam nec molestie porta. Mauris sed egestas lectus, at imperdiet quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis dolor eu metus blandit laoreet. Maecenas facilisis nibh sit amet dictum faucibus. Ut in pretium purus. In consectetur eleifend elementum. Suspendisse vel est luctus, semper ex et, vestibulum nulla. Sed ultricies leo lectus, vitae sollicitudin lorem lacinia at.
    </div>
  )
}

export default LazyComponent;